version: '3.8'

services:
  app:
    build: .
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
    command: >
      sh -c "npx prisma generate && npm run start"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    env_file:
      - .env
